export const users = [
  {
    id: 1,
    name: 'Dulcia',
    gender: 'Female',
    email: 'dhanburybrown0@wired.com',
    country: 'China',
    birthday: '09/03/2003',
  },
  { id: 2, name: 'Lenka', gender: 'Female', email: 'lmapham1@posterous.com', country: 'Egypt', birthday: '03/07/1953' },
  {
    id: 3,
    name: 'Kira',
    gender: 'Female',
    email: 'kjimpson2@blinklist.com',
    country: 'Trinidad and Tobago',
    birthday: '17/04/1964',
  },
  { id: 4, name: 'Monte', gender: 'Male', email: 'msharnock3@jigsy.com', country: 'Canada', birthday: '06/01/1961' },
  { id: 5, name: 'Reilly', gender: 'Male', email: 'rfilipczak4@google.ca', country: 'Panama', birthday: '12/07/1973' },
  {
    id: 6,
    name: 'Butch',
    gender: 'Male',
    email: 'bjachtym5@guardian.co.uk',
    country: 'Russia',
    birthday: '23/11/1952',
  },
  {
    id: 7,
    name: 'Melisa',
    gender: 'Female',
    email: 'mkobisch6@imgur.com',
    country: 'Colombia',
    birthday: '27/07/1988',
  },
  {
    id: 8,
    name: 'Carolus',
    gender: 'Male',
    email: 'ctrudgian7@weather.com',
    country: 'Portugal',
    birthday: '26/08/1954',
  },
  {
    id: 9,
    name: 'Ced',
    gender: 'Male',
    email: 'cjouannisson8@theglobeandmail.com',
    country: 'Brazil',
    birthday: '04/06/1989',
  },
  { id: 10, name: 'Ricki', gender: 'Female', email: 'rbamling9@ucla.edu', country: 'China', birthday: '06/07/1968' },
];
